name: PR Build

on:
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BUILD_VER: 1.0.${{ github.run_number }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x
      - name: Prep packages
        run: dotnet nuget add source --username guypritchard --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/guypritchard/index.json"
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore -p:Version=${{ env.BUILD_VER }}
      - name: Test
        run: dotnet test --no-restore --verbosity normal
